import { NextRequest, NextResponse } from 'next/server';
import { getValidTokens, getRWPlaylistTracks, getSpotifyUser, createPlaylist } from '@/lib/spotify';
import { matchArtistsToTracks } from '@/lib/matcher';
import { getLineupData } from '@/lib/lineup';
import type { Artist } from '@/types/lineup';
import { DAY_LABELS } from '@/types/lineup';

export async function POST(request: NextRequest) {
  const tokens = await getValidTokens();
  if (!tokens) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  }

  const body = await request.json();
  const { artistIds, maxTracksPerArtist = 5 } = body as {
    artistIds: string[];
    maxTracksPerArtist?: number;
  };

  if (!artistIds || artistIds.length === 0) {
    return NextResponse.json({ error: 'No artists provided' }, { status: 400 });
  }

  try {
    const lineup = await getLineupData();
    const allArtists: Artist[] = lineup.flatMap((day) =>
      day.stages.flatMap((stage) => stage.artists),
    );
    const selectedArtists = allArtists.filter((a) => artistIds.includes(a.id));

    const tracks = await getRWPlaylistTracks(tokens.accessToken);
    const result = matchArtistsToTracks(selectedArtists, tracks, maxTracksPerArtist);

    if (result.totalTracks === 0) {
      return NextResponse.json({ error: 'No tracks matched — nothing to add to playlist' }, { status: 400 });
    }

    const user = await getSpotifyUser(tokens.accessToken);

    const selectedDays = [...new Set(selectedArtists.map((a) => a.day))];
    const dayStr =
      selectedDays.length <= 2
        ? selectedDays.map((d) => DAY_LABELS[d]).join(' & ')
        : 'All Days';

    const playlistName = 'Rock Werchter 2026 — My Selection';
    const description = `${dayStr} | ${selectedArtists.length} artists, ${result.totalTracks} tracks | Generated by RW Planner`;

    const trackUris = result.matchedArtists.flatMap((a) => a.tracks.map((t) => t.uri));

    const playlist = await createPlaylist(user.id, playlistName, description, trackUris, tokens.accessToken);

    return NextResponse.json({
      ok: true,
      playlistId: playlist.id,
      playlistUrl: playlist.url,
      totalTracks: result.totalTracks,
    });
  } catch (err) {
    console.error('[/api/spotify/create] Error:', err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
