import { NextRequest, NextResponse } from 'next/server';
import {
  addMissingTracksToPlaylist,
  createPlaylist,
  getSpotifyUser,
  getValidTokens,
  searchTracksByArtist,
  SpotifyApiError,
  SPOTIFY_SCOPES,
} from '@/lib/spotify';
import { getLineupData } from '@/lib/lineup';
import { compareArtistsChronologically, DAY_LABELS, type Artist } from '@/types/lineup';
import type { MatchedArtist } from '@/types/spotify';

export async function POST(request: NextRequest) {
  const tokens = await getValidTokens();
  if (!tokens) {
    return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  }

  const body = await request.json();
  const {
    artistIds,
    maxTracksPerArtist = 5,
    targetPlaylistId,
    trackUris: explicitTrackUris,
    playlistName: requestedName,
  } = body as {
    artistIds: string[];
    maxTracksPerArtist?: number;
    targetPlaylistId?: string;
    trackUris?: string[];
    playlistName?: string;
  };

  if (!artistIds || artistIds.length === 0) {
    return NextResponse.json({ error: 'No artists provided' }, { status: 400 });
  }

  try {
    const lineup = await getLineupData();
    const allArtists: Artist[] = lineup.flatMap((day) =>
      day.stages.flatMap((stage) => stage.artists),
    );
    const selectedArtists = allArtists
      .filter((a) => artistIds.includes(a.id))
      .sort(compareArtistsChronologically);

    let trackUris = [...new Set(explicitTrackUris ?? [])];
    if (trackUris.length === 0) {
      // Search tracks per artist in parallel
      const results = await Promise.allSettled(
        selectedArtists.map((artist) =>
          searchTracksByArtist(artist.name, tokens.accessToken, maxTracksPerArtist),
        ),
      );

      const matchedArtists: MatchedArtist[] = selectedArtists.map((artist, i) => {
        const result = results[i];
        const tracks = result.status === 'fulfilled' ? result.value : [];
        return {
          festivalArtistId: artist.id,
          festivalArtistName: artist.name,
          matched: tracks.length > 0,
          tracks,
        };
      });

      trackUris = [...new Set(matchedArtists.flatMap((a) => a.tracks.map((t) => t.uri)))];
    }

    if (trackUris.length === 0) {
      return NextResponse.json({ error: 'No tracks matched — nothing to add to playlist' }, { status: 400 });
    }

    const user = await getSpotifyUser(tokens.accessToken);

    const selectedDays = [...new Set(selectedArtists.map((a) => a.day))];
    const dayStr =
      selectedDays.length <= 2
        ? selectedDays.map((d) => DAY_LABELS[d]).join(' & ')
        : 'All Days';

    const customName = typeof requestedName === 'string' ? requestedName.trim().slice(0, 100) : '';
    const playlistName = customName || 'Rock Werchter 2026 — Mijn selectie';
    const description = `${dayStr} | ${selectedArtists.length} artists, ${trackUris.length} tracks | Generated by RW Planner`;

    console.info('[/api/spotify/create] Saving selection to playlist', {
      spotifyUserId: user.id,
      selectedArtistCount: selectedArtists.length,
      trackCount: trackUris.length,
      selectedDays,
      playlistPublic: false,
      targetPlaylistId: targetPlaylistId ?? null,
      requestedScopes: SPOTIFY_SCOPES,
    });

    if (targetPlaylistId) {
      const addResult = await addMissingTracksToPlaylist(targetPlaylistId, trackUris, tokens.accessToken);
      return NextResponse.json({
        ok: true,
        playlistId: targetPlaylistId,
        playlistUrl: `https://open.spotify.com/playlist/${targetPlaylistId}`,
        totalTracks: addResult.addedCount,
        addedTracks: addResult.addedCount,
        skippedTracks: addResult.skippedCount,
        requestedTracks: addResult.requestedCount,
        mode: 'existing',
      });
    }

    const playlist = await createPlaylist(playlistName, description, trackUris, tokens.accessToken);

    return NextResponse.json({
      ok: true,
      playlistId: playlist.id,
      playlistUrl: playlist.url,
      totalTracks: trackUris.length,
      addedTracks: trackUris.length,
      skippedTracks: 0,
      requestedTracks: trackUris.length,
      mode: 'new',
    });
  } catch (err) {
    if (err instanceof SpotifyApiError) {
      console.error('[/api/spotify/create] Spotify API error', err.details);
      return NextResponse.json(
        {
          error: err.message,
          spotify: err.details,
          requestedScopes: SPOTIFY_SCOPES,
        },
        { status: err.details.status },
      );
    }

    console.error('[/api/spotify/create] Error:', err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
